### ISSUE TITLE
Only last occurrence of `maxage` applied

### ISSUE THREAD

**Issue by stefanv** [OfflineIMAP/offlineimap#105]
When specifying different values of `maxage` for separate accounts, only the last value is taken into consideration.

**Comment by nicolas33** [comment]
I wonder if it's related with #143...

**Comment by nicolas33** [comment]
* Could you share your configuration file, please?
* Do you use Py2?

**Comment by stefanv** [comment]
I guess a first question would be: should it be possible to specify maxage for each folder?  I had one account, but several folders that I wanted to treat differently (e.g., don't care to fetch sent mail older than a month, but fetch up to 6 months for the rest).

**Comment by nicolas33** [comment]
This is another topic. Currently, maxage applies to the whole account but I agree that a per-folder setting would make sense.

Janna Martl is currently revamping the whole maxage machinery because he found issues with the processing logic. I think his work is near to the end but he might agree to implement it. Don't know.

 Feel free to open a new issue about that.

**Comment by spaetz** [comment]
NOOO! :-) Our configuration is overly complex as it is. Use different accounts if you need different maxages, that is possible today, but don't let us introduce per-folder differences for maxage.

**Comment by stefanv** [comment]
I don't mind which option gets chosen; but documenting that choice would be
very helpful.
