### ISSUE TITLE
systemd integration

### ISSUE THREAD

**Issue by zabbal** [OfflineIMAP/offlineimap#109]
Would be nice to see systemd integration included upstream - at least .service file. This way we avoid code duplication and allow users to use it in convenient way right out of the box. An examples can be taken from http://babushk.in/posts/offlineimap-systemd.html

**Comment by nicolas33** [comment]
Submit a patch, please.

**Comment by nicolas33** [comment]
Done.

**Comment by simonbcn** [comment]
The systemd files in package use timer units to execute it every n minutes.
Why are not the program's capabilities used to do that task?
With the program config I can configure the minutes between syncs and if it does a full or quick sync. With timers this isn't possible.

**Comment by mathstuf** [comment]
I use timers because offlineimap would drop accounts that became unresponsive until restarted. Also, GMail rotates their certificates every few weeks and I need to add fingerprints to the configuration file when that happens which requires a restart anyways.

Personally, I have the unit files in my dotfiles repo anyways (also because sometimes I run offlineimap from a custom build rather than the package and changing in a home directory is easier than from the system).
