### ISSUE TITLE
Use imaplib2 version which support Python 3

### ISSUE THREAD

**Issue by frabcus** [OfflineIMAP/offlineimap#122]
This https://github.com/bcoe/imaplib2/pull/4 (which is on the repo that pypi now links to for imaplib2) pull request makes imaplib2 support Python 3.

Can offlineimap change to use it?

**Comment by nicolas33** [comment]
I couldn't find easily what version of imaplib2 has this patch. Anyway, I don't think OfflineIMAP is Py3 compatible, is it?

**Comment by frabcus** [comment]
"I couldn't find easily what version of imaplib2 has this patch." - it's merged into master, so this code here: https://github.com/bcoe/imaplib2. Alas, they haven't bumped the version number or released to PyPi since then :( I've filed a bug asking for that: https://github.com/bcoe/imaplib2/issues/6

"Anyway, I don't think OfflineIMAP is Py3 compatible, is it?" - The whole point of this issue is to lead towards OfflineIMAP being Py3 compatible, so that seems a strange question!

**Comment by nicolas33** [comment]
> it's merged into master, so this code here: https://github.com/bcoe/imaplib2. Alas, they haven't bumped the version number or released to PyPi since then :( I've filed a bug asking for that: bcoe/imaplib2#6

Fine, will wait until a stable release. I'm not following impalib2 releases (my bad). So, feel free to tell us once it's done.

> The whole point of this issue is to lead towards OfflineIMAP being Py3 compatible, so that seems a strange question!

Not that much. I didn't contribute to OfflineIMAP for a long time. I was not sure of the state of OfflineIMAP about Py3. Since I know OfflineIMAP never supported py3 I know this issue is non-critical for the coming releases.

**Comment by frabcus** [comment]
https://pypi.python.org/pypi/imaplib2/2.37.4 is now released and on PyPi, and supports Python 3.

So I think OfflineIMAP can be updated to use it now.

Am wondering, can OfflineIMAP now use the version from PyPi instead of including it inline? e.g. As a dependency in `setup.py`

**Comment by nicolas33** [comment]
Thank you.

> Am wondering, can OfflineIMAP now use the version from PyPi instead of including it inline? e.g. As a dependency in setup.py

I wonder if it would actually be a good idea. We have some glitches with imaplib2, for years. Embedding it gives us more predicable handling on them and allow us to *restrict* impacts up to a certain point.

**Comment by spaetz** [comment]
I think bundling is still a good idea as not many distros package imaplib2. But allowing to install iamplib2 via pypi via setup.py would be a neat thing in general.

**Comment by nicolas33** [comment]
>  But allowing to install iamplib2 via pypi via setup.py would be a neat thing in general.

But why for?

**Comment by spaetz** [comment]
Because it is the "right" way to handle 3rd party dependencies? :-)
Bundlijng might be the best way really, it is a rather small library and we can rely on the behavior of a specific version.

**Comment by nicolas33** [comment]
imaplib2 was designed to be embedded and it's still a one file library. That's why I don't get the point of using pypi instead of historical embedding. I don't get for *what* use case.

Also, I'm wondering if imaplib2 will keep the pypi way in the long run. Years ago, it was mainly a one guy project and I expect this will remain true.

As a consequence, If anyone implement it it's fine but I won't do it myself.

**Comment by xiaket** [comment]
hi, all.

  I've implemented a version of offlineimap that do not include imaplib2 inline. I would send a pull request soon. The problem is that my tweak is twisted with other modifications(auto decode/encode utf7 string, added socks proxy support for example), so I need some time to separate them. Stay tuned.

**Comment by nicolas33** [comment]
Ok. Can you publish the WIP somewhere so I can give you my first comments?

**Comment by xiaket** [comment]
#168 . Oops, I just found that this commit kind of conflicts with the work of @konvpalto , who just added traceback for branch `next` in 7ab779ab21dcf4f33b6a

**Comment by nicolas33** [comment]
Not a problem. This is WIP. ,-)

**Comment by nicolas33** [comment]
Bumped to the last version of imaplib2 2.41.
