### ISSUE TITLE
offlineimap erroneously maps T => \Deleted

### ISSUE THREAD

**Issue by rnkn** [OfflineIMAP/offlineimap#142]
I'm using FastMail + offlineimap + mu4e.

The default FastMail Trash folder behaviour is to auto-purge messages in the folder after 60 days and immediately purge all messages with the `\Deleted` IMAP flag.

The mu4e "trash" behaviour is to move to the Trash folder and apply the Maildir `T` (trashed) flag. The "delete" behaviour is to permanently delete the file.

This pretty standard behaviour is obviously to allow a buffer of time between "trashing" an email and having it erased.

However, offlineimap is mapping `T` => `\Deleted` which causes emails to be immediately deleted. The `T` flag is *not equivalent* to the `\Deleted` IMAP flag (see <http://cr.yp.to/proto/maildir.html>).

Both FastMail staff and mu/mu4e creator @djcb (see <https://groups.google.com/forum/#!topic/mu-discuss/m4ORymDlf0E>) have confirmed that this is erroneous behaviour.

Can you please stop mapping `T` => `\Deleted`?

**Comment by nicolas33** [comment]
> Given that there seem to be two opposed schools of thought on what the right way is, maybe allowing for both is in everyone's best interests?

Don't know but since you could fix your issue, I'm closing.

**Comment by xmaillard** [comment]
I do not call that a "fix". Don't you think you should take the time to analyze whether it is a good proposition or not ? We are a few expecting such modification.

If you are not willing to do it, could you at least explain where we could try by ourself in the code ?

Regards

**Comment by nicolas33** [comment]
Well, the "workaround" of re-assigning the "d" key binding can fix the operations to what you expect.

Other than that, I'm closing the issue mostly because I don't want do debate of what means a non-standard flag (then not well-defined by definition according to software programming).

Though and to make it clear, I'm willing to merge a patch to change the way OfflineIMAP works. Be care that such a change *requires* an option to not break current users expectations.

I have to say that while I'm not going to do such job myself, I'm fine to help anybody with the OfflineIMAP source code, git and whatever can help to do the task, like I always did. *BUT* I'm not going to do your *home work*. If someone come with a specific question I would be very happy to answer.

Consider starting with the [online development documentation](http://docs.offlineimap.org/en/latest/).

Last but not least, I expect such development related work to happen in the mailing list. Mails are much faster and easier to work with for such task.

Regards

**Comment by spaetz** [comment]
Hi, I checked out the links to the threads you provided:
- issue #107 wants "deleted" mails to correspond to a "\Trash" label, something which is absolutely non-standard. I have no clue why Gmail decides to remove messages from folders that have a deleted flag, but given their weird way of exposing tags via IMAP folders all bets are off for Gmail anyway. 

- as for https://groups.google.com/forum/#!topic/mu-discuss/z4w_Gy1w6vg
The only one who voices any kind of concern are the two of you who are also very vocal here. It is kind of an exaggeration to use this thread as a proof that it has also confused lots of other people.

- as for: https://groups.google.com/forum/#!topic/mu-discuss/y6T-MpWKXh4
This is an issue that the users local IMAP server web interface has been configured to not display any message with a Trash flag, according to the user, I don't see any Maildir involved at all (the user uses IMAP<->IMAP)

OfflineImap has been doing this since 2001, and not once has this behaviour been questioned before. And many advanced IMAP experts have been involved in its development (not counting me). So excuse me if I say, that your interpretation of the flags might not be universally be shared. You solved your issue by simply "MOVING" mails to the Trash folder, which is exactly what you want to do.

As for the literary analysis digresion (I love digressions), I disagree with the metaphors being used. "Moving a mail to the Trash folder, is throwing it in the attic (or bin if you want)", it is recoverable if you want. Putting on a "T" flag means, it is outside your house in the container. The IMAP "deleted" flag is nothing different. Actually, my client shows deleted messages on the server just fine, just crossed through and ready for undeletion. Calling that throwing in the fireplace is not the correct metaphor.

Altogether, I am happy that you found the solution of actually just moving a mail to the trash folder via a key binding, this is what is the right thing to do. Servers auto-expunging deleted mail are a tad overzealous.

All this will probably not make you happy, but there is, in my opinion no bug to fix in this case.

**Comment by jgoerzen** [comment]
OfflineIMAP is correct here.  The bug is in mu4e and I have submitted it there: https://github.com/djcb/mu/issues/1136

**Comment by nicolas33** [comment]
Hi John!

How are you? Thanks for your hint and report.

**Comment by jgoerzen** [comment]
Hi Nicolas!  Good to be chatting with you again (even in a Github issue box <grin>)  I'm well.  OfflineIMAP is slowly starting to creep back into my life, due partly to its support for GMail OAuth2 and partly to the increasing quality of Emacs mail clients and (IMHO) decreasing quality of Thunderbird.  It is pretty amazing to see how just about every Emacs mail client has instructions for setup with OfflineIMAP.

Thanks for all your work maintaining and enhancing it!  Really nice to see what it's become.

**Comment by nicolas33** [comment]
Thank you. Happy to see you here again. I agree contributors are doing a wonderful job.
