### ISSUE TITLE
offlineimap 6.5.4 sync original date and time 

### ISSUE THREAD

**Issue by naveensharmayoung** [OfflineIMAP/offlineimap#157]
i am using offlineimap with squirrelmail while accesing the mails via squirrelmail i got system time of emails but i want the original time and date  of email after sync

**Comment by naveensharmayoung** [comment]
thanks for the reply, i am new to offlineimap, kindly share the details about the feature as mentioned from your site to get the synchronized date time in the mails. The process to recieve the mails is offlineimap-->dovecot-->squirrelmail. currently the date got synchronized but fetching the system time.

**Comment by nicolas33** [comment]
IOW, you'd like the mail files in your Maildir to have the modification time matching the `Date` header of the mail, right?

**Comment by naveensharmayoung** [comment]
yes the squirrelmail only show dates(original) of my mails but the time it takes system time for all mails 
 for eg. 
gmail ->> 12:30 pm 2/1/2010 
but squirrelmail show
mail->>    4:30 pm 2/1/2010(only dates got exact same as mail)
4:30 is the system time when i sync the mails using offlineimap not original time

**Comment by naveensharmayoung** [comment]
please suggest the solution to my problem is their is timezone addjustment required or something else

**Comment by nicolas33** [comment]
I know we have filesystem time tuning about files in the code. I can't remember why but I guess your issue comes from there.

We might need a new CLI options to allow better control of what OfflineIMAP does in this area, I didn't check.

While I think the issue comes from OfflineIMAP, I believe it's a very unusual use case coming from the tool chain you describe. That's why you shouldn't expect a fix soon, unless you involve yourself in the code. Another option would be to fetch your mails to Dovecot with another tool. Doesn't Dovecot provides such a feature, BTW?

**Comment by naveensharmayoung** [comment]
yes dovecot provide this feature also so how your offlineimap different from dovecot

**Comment by nicolas33** [comment]
I can't tell, I don't know Dovecot enough.

What I understand is that you're feeding Dovecot's *Maildir database* behind his back. So, I'm not surprised that any Dovecot assumptions about its own data are not met at some point. And that's why I talked about a *very unusual use case* coming *from the tool chain*.

While the initial request seems legit at a first glance, I'm not sure we want to match/support assumptions of all IMAP servers (using a Maildir database) out there.

I think we first have to check if our Maildir is wrong but I'm pretty sure the standard is light enough to not require anything in this area.

http://wiki2.dovecot.org/MailboxFormat/Maildir

**Comment by naveensharmayoung** [comment]
i want to sync 100 gmail accounts to a local drive only need one way. It is wise to use offlineimap or not

**Comment by nicolas33** [comment]
Can't tell much for you. You have to make your own tests.

Look at all [Gmail issues](https://github.com/OfflineIMAP/offlineimap/labels/Gmail) or more globally all current open issues.
Also, read the [Known bugs](http://docs.offlineimap.org/en/latest/MANUAL.html#known-bugs) section and the [FAQ](http://docs.offlineimap.org/en/latest/FAQ.html) carefully.

Apart my reserves about the tool chain, I think it should be fine as long as Gmail won't mess their UIDs. I would split the configurations, one per account.

**Comment by naveensharmayoung** [comment]
i want to participate in the offlineimap development i am currently in the network administrator field  in a indian company how can i help you to enhance the offlineimap i am a big fan of this application

**Comment by nicolas33** [comment]
Sorry, looks like I've missed this comment (I wonder if github notifications are working well, BTW).

You're welcome and you'll be our tester if you still want to apply.

First thing is to fork the git repo and subscribe to the mailing list (this is where interesting things happen). Then, I'd like to let you discover how to contribute effectively without more hints. If you need help, request us on the mailling list. Your feedbacks could help us improving the documentation for new comers. ,-)

**Comment by nicolas33** [comment]
I'm closing since I guess few users would need this.
