### ISSUE TITLE
sending internal date with incorrect timezone

### ISSUE THREAD

**Issue by mjhoy** [OfflineIMAP/offlineimap#186]
Hello,

I use offlineimap to sync my fastmail account. I noticed that on the fastmail web interface the emails I had sent locally, and synced up to the fastmail sent folder via offlineimap, reported dates that were 1 hour off (in the future).

A bit of talking with fastmail support, I think I found the issue: offlineimap sends date metadata (this is the "internaldate" in imap protocol, I think?) that is not the correct timezone.

Here is what I think is the relevant portion of the output from running ```offlineimap -d imap```:

https://gist.githubusercontent.com/mjhoy/63e1a1c5d1d408a33285/raw/7111a4f280d13e37ff7d85b333db293fb2775782/gistfile1.txt

The date header in my test email is set to Mon, 30 Mar 2015 14:03:50 -0400. However there is this line:

```[imap]:   05:05.70 mail.messagingengine.com writer > DLKE23 APPEND "INBOX.Sent Items" (\Seen) "30-Mar-2015 14:03:51 -0500"```

Which I believe is offlineimap reporting the incorrect time (-0500 instead of -0400).

Regardless of what my system timezone is set to: Shouldn't the internaldate always be the same as whatever is in the Date header? If my system is the issue, I'm on OS X 10.9, my timezone is set to -0400.

Offlineimap version 6.5.5.

My email client is emacs.

Thanks, and apologies if I'm misunderstanding what IMAP is supposed to do or what the protocol is.
Mike

**Comment by nicolas33** [comment]
Here is how it works. The code is really straightforward in this area. ;-)

Pushing a mail on remote IMAP is called "APPEND". This is done in the [savemessage() method](https://github.com/OfflineIMAP/offlineimap/blob/next/offlineimap/folder/IMAP.py#L498).

This method applies the date as returned by the [__getmessageinternaldate() method](https://github.com/OfflineIMAP/offlineimap/blob/next/offlineimap/folder/IMAP.py#L422).

The local Maildir does NOT have real INTERNALDATE (as defined by IMAP standard). We fake it with the values taken from the `rtime` parameter (coming from [getmessagetime()](https://github.com/OfflineIMAP/offlineimap/blob/next/offlineimap/folder/Maildir.py#L243), the modification time of the file) and fallback to the header if it looks wrong.

I'm giving you the details because you might want to insert debug `print` statements to get where it might fail. The comments in the code are helpfull.

**Comment by mjhoy** [comment]
Awesome, thanks! I will look into it.

**Comment by nicolas33** [comment]
Also, there was changes around dates and times recently. Please check against v6.5.7-rc4.

**Comment by mjhoy** [comment]
Testing against v6.5.7-rc4 still does not work.

I believe I've narrowed down the problem to https://github.com/OfflineIMAP/offlineimap/blob/next/offlineimap/folder/IMAP.py#L492

The check against `datetuple.tm_isdst` always fails; it should be checking against the integer 1, not the string '1'. The python documentation seems to specify this as well: https://docs.python.org/2/library/time.html#time.struct_time

This fixed the problem for me:

https://github.com/mjhoy/offlineimap/commit/9baef00a0b02c46aaf3110a246eb366adb51f375

I can send a pull request if you'd like.

**Comment by nicolas33** [comment]
Nice, please [read this](http://offlineimap.org/doc/dco.html) so I can apply the patch.

**Comment by nicolas33** [comment]
Thank you much! Applied.
