### ISSUE TITLE
Sub-folder with a . (period) in the name report UID validity problem

### ISSUE THREAD

**Issue by lrochfort** [OfflineIMAP/offlineimap#227]
I'm running 6.5.7.

When attempting to sync a subfolder with a . (period) in the name, syncing fails with the UID validity error.

In the log the subfolder name has the . replaced with a /.

In the Maildir I see two folders. One with everything in the name up to the period and another with the full name.

e.g. For folder "MyFolder/SubFolder 1.5", I see MyFolder 1/5 reported in the log and "MyFolder.MyFolder 1" and "MyFolder.MyFolder 1.5" in my Maildir.

**Comment by nicolas33** [comment]
I would not be surprised we realize the reported sep are incorret in the logs. This would need to be checked first.

I wonder if the UID validity error is real regardless the dots. Perhaps the mail provider did changed the folders with a dot and not the others.

Do you still have the problem with a fresh configuration file, metadata path and a new maildir path?

**Comment by lrochfort** [comment]
Yes, the problem persists even with a clean setup.

In the meantime I just removed the folders with the dot in their name.

**Comment by nicolas33** [comment]
Well, since the dot is  considered a separator, I think that OfflineIMAP tries to sync with another existing folder.

If there's no folder name matching the wrong translated folder name, there is a bug because OfflineIMAP should report a non existing folder.

There is the sep configuration option. If you want to use dots in folder names, you should put another character here. A character that you won't use in any folder name, obviously.

**Comment by nicolas33** [comment]
dups #148
