### ISSUE TITLE
offlineimap in cron with remotepasseval and pythonfile: "Prompting for a password is not supported in this UI backend."

### ISSUE THREAD

**Issue by williamsmj** [OfflineIMAP/offlineimap#25]
I use a simple Python script to get my IMAP password from Keychain on OS X. If I run `offlineimap -u basic` from the command line, the configuration below works fine. No user interaction is required. If I put the same command in my crontab, I get the following error in the email report from cron:

```OfflineIMAP 6.5.4
  Licensed under the GNU GPL v2+ (v2 or any later version)
*** Processing account email
Establishing connection to imap.server.com
ERROR: While attempting to sync account 'email'
  Prompting for a password is not supported in this UI backend.
*** Finished account 'email' in 0:01
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'mpe'
  Prompting for a password is not supported in this UI backend.```

Am I missing something?

Here's the configuration file, with server info changed to protect the innocent.

```[general]
accounts = email
pythonfile = /usr/bin/get_pw.py

[Account email]
localrepository = local
remoterepository = remote

[Repository local]
type = Maildir
localfolders = ~/.mail/

[Repository remote]
type = IMAP
remotehost = imap.server.com
remoteuser = user
remotepasseval = get_pw("imap.server.com")```

**Comment by nicolas33** [comment]
Could you please test with latest v6.5.7-rc2?

**Comment by williamsmj** [comment]
Sorry, I don't have an easy way to test this setup any more.

**Comment by roorco** [comment]
Me too, not even on Linux unfortunately. 
Off topic:
Back too windows and everything seems to me so obsolete. Didn't realize it before. 



—

**Comment by nicolas33** [comment]
I'm not surprised, it's a pretty old issue. Thank you both for replying anyway!

**Comment by FedericoVaga** [comment]
I have the same issue. Fedora 22 comes with 6.5.6, so I downloaded the last version but the problem is still there.

> Prompting for a password is not supported in this UI backend.

In cron I'm running the following command

> offlineimap -o -u quiet

**Comment by bchallenor** [comment]
I am seeing the same behaviour with 6.5.7 on Mac.

The issue seems to be that `keyring`, the Python lib I am using to access the keychain, is not finding the password when run in cron's context. Its `get_password` function is returning `None`.

I suspect what is happening at this point is that offlineimap is continuing on from the `None` and prompting for a password, as if `remotepasseval` was not even set. I think to avoid confusion, it should probably detect the `None` and blow up instead of silently falling back to a password prompt.

The root cause, though, is not offlineimap's fault. I just don't think you can access the Mac login keychain from cron's context. For example, if I put `security list-keychains` in cron, it doesn't even show the login keychain.

**Comment by nicolas33** [comment]
Good to know. It might worth mentioning it in the configuration file.

**Comment by bchallenor** [comment]
What do you think about the idea of throwing an error if `remotepasseval` returns `None`? I think this is pretty likely to be a configuration mistake that the user wants to know about. I can't think of a situation in which the current fallback-to-prompt behaviour is useful.

**Comment by nicolas33** [comment]
I think it would be an improvement that might worth. The password internal is not simple, though. So it must be well thought.
