### ISSUE TITLE
offlineimap.conf.minimal should have some hints about configuring TLS.

### ISSUE THREAD

**Issue by nuket** [OfflineIMAP/offlineimap#263]
Got bitten by the default offlineimap.conf.minimal connecting to what I believe was an unencrypted port 143 and starting its operations.

It would be very helpful if offlineimap.conf.minimal had a few hints about configuring SSL connections, and had "ssl = yes" set by default.

**Comment by nicolas33** [comment]
I don't get the point. Minimal stands for what it is: a *minimal* configuration file. This helps to figure out what's mandatory to get started but won't help much at setting things plain right.

I guess that in the next two weeks, someone else will complain that he's got bitten by the default ssl protocols (or whatever) not matching its use case. And in the next month, someone else will complain about yet another expectation he had as a default value and missing from the minimal conf. In the end we would have the full documentation in the minimal configuration file. :-1: 

I'm not pretending that the default ssl value can't be change. I'm pointing out that the minimal config should stay minimal, IMHO.

This might worth encouraging the user to make some checks about security options, though. But this would be a very small comment. No more.

Also, you should read http://offlineimap.org/doc/dco.html. ,-)

**Comment by nuket** [comment]
The point is that the minimal config makes no mention that it is 
insecure by default, and that by simply replacing the values in the 
Remote configuration block, anyone using it will be transferring all of 
their emails in the clear.

At the very least, I would expect comments to this effect. And I would 
expect the necessary parameters, commented out if necessary, to be 
present in the file to be easily activated. tl;dr, the three directives 
that I put in the minimal config would suffice.

What I don't expect is to copy the minimal config to .offlineimaprc, 
modify it for my server, and get no warning as OfflineIMAP connects 
unencrypted to 143 and starts dumping my email.

**Comment by nicolas33** [comment]
Ok. I'll finally allow security matter enter the minimal conf if you want because it's security. You conviced me. ,-)

However, notice that your patch fails at protecting the user in the IMAP/IMAP case. I can think of two ways to accomplish the purpose:

###### light policy 

Encourage the user to look further for security options. Everything must be comments in the minimal config and must explain the points we discussed here:
* have a sample with the minimal options to get a secured connection;
* tell this is just minimal;
* point to offlineimap.conf.

###### strong policy

A more stricter policy would be to simply set `ssl = yes` the default. This would **force** the user to check the options related to security.


I let you the choice about how to do that. :-)

**Comment by nuket** [comment]
Ok, I think the strong policy makes sense with some extra comments here.

I've added an explanation about these options only applying to the specific [Repository] block.

Since offlineimap currently seems to break on Windows (due to dependency on the fcntl module), the primary users of this are probably OS X and Linux users. I trust the basic competence of the user in figuring out how to set up two new options in the minimal conf.

**Comment by nicolas33** [comment]
Last patch is confused about what default is. What I meant is that OfflineIMAP should have ssl enabled by default if `ssl` option **is not defined**. Since ssl requires configuration to work, the user would be **forced** to look further.
At least, this would fully achieve the "don't send any data in the wild" while keeping the minimal config sane and **minimal**. We should avoid replicating comments over differents files.

So, either hihglight this is a minimal and potentially dangerous configuration file or make the software safer with stronger default options.

**Comment by nuket** [comment]
SSL is now on by default in the code.

**Comment by nicolas33** [comment]
Great! Applied squashed commits with minor changes in commit message.
Thanks!
