### ISSUE TITLE
Unknown namespace on second sync

### ISSUE THREAD

**Issue by amandabee** [OfflineIMAP/offlineimap#269]
I ran `offlineimap` once and it took nearly 24 hrs but it did sync my mailboxes. Fabulous. Tried to run it a second time and got the following error:

    ERROR: Folder 'Sent'[Remote] could not be created. 
    Server responded: ('NO', ['Unknown namespace.'])

The full error is below. I've searched around and I don't see any solutions that address the "unknown namespace" portion.

Thanks for any leads?

```
amanda@giselle:~$time offlineimap
OfflineIMAP 6.5.5
  Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync Dinosaur:
 *** Processing account Dinosaur
 Establishing connection to mail.dinosaur.info:993
 Creating folder Sent[dRemote]
 ERROR: Creating folder Sent on repository dRemote
  Folder 'Sent'[dRemote] could not be created. Server responded: ('NO', ['Unknown namespace.'])
 ERROR: Folder 'Sent'[dRemote] could not be created. Server responded: ('NO', ['Unknown namespace.'])
 *** Finished account 'Dinosaur' in 0:01
ERROR: Exceptions occurred during the run!
ERROR: Creating folder Sent on repository dRemote
  Folder 'Sent'[dRemote] could not be created. Server responded: ('NO', ['Unknown namespace.'])
```

**Comment by johnmastro** [comment]
I'm not an `offlineimap` developer but encountered something similar in the past.

In my case (on FastMail), the issue was that the `Sent` folder on the remote end was actually called `INBOX.Sent Items` (aka it's in the `INBOX` namespace). In fact, for me this applies to all folders - `Archive` becomes `INBOX.Archive` and so on.

Here's the `nametrans` rule I use to prepend local folder names with `INBOX.`:

```python
nametrans = lambda folder: {'inbox'  : 'INBOX',
                            'archive': 'INBOX.Archive',
                            'drafts' : 'INBOX.Drafts',
                            'sent'   : 'INBOX.Sent Items'
                           }.get(folder, 'INBOX.' + folder)
```

Something like that would go in the configuration for your local repository (the one with `type = Maildir`.

**Comment by amandabee** [comment]
@johnmastro this was hugely helpful.

And ... in examining exactly what `nametrans` rules I would need I figured out that actually Mutt had created the "Sent" folder and I moved it out of the way and sync works now. But I wouldn't have worked that out without trying to figure out how your solution fit my directory structure.

**Comment by johnmastro** [comment]
Glad it helped!
