### ISSUE TITLE
How to let offlineimap to sync all email in my email server (even synced before)

### ISSUE THREAD

**Issue by zw963** [OfflineIMAP/offlineimap#310]
### General informations

- OfflineIMAP 6.5.7
- server name or domain:
- CLI options: NO
- configuration (remove private data):
```
[general]
accounts = netease
maxsyncaccounts = 2
pythonfile = ~/Dropbox/common/personal/imap4-utf7.py
socktimeout=30
fsync=false

[Account netease]
localrepository = LocalNetease
remoterepository = RemoteNetease
maxage = 365

[Repository LocalNetease]
type = Maildir
localfolders = ~/Maildir/netease
nametrans = lambda foldername: foldername.decode('utf-8').encode('imap4-utf-7')
[Repository RemoteNetease]
type = IMAP
remotehost = imap.163.com
remoteuser = MY_USER_NAME
nametrans = lambda foldername: foldername.decode('imap4-utf-7').encode('utf-8')
cert_fingerprint = 9d3927e5ec44dac6f8a9a31b8150e1c824341681
realdelete = yes
subscribedonly = no
ssl=yes
maxconnections = 2
createfolders = False
```

When I run offlineimap from terminal, it always sync newest email in my server.
this is expected correct behavior, anyway.

I think offlineimap change something on my email server, although, synced email
still marked as unread on my email server.

The problem is:

1.  How to mark my email server as read when synced.
2.  When I accidentally delete my local Maildir (current case),
I want to sync all email which still in my server, but this not happen.
it only sync only a little newest email, what i do is clone all exist email 
to my local Maildir.

Thanks.

**Comment by nicolas33** [comment]
1. This feature is not implemented. You have to mark them as read on one side so the flags get synced to the other side on next run.

2. Partial syncs for a mailbox/folder is not possible (outside of date limitations and maxsize when configured in the configuration file). So yes, you have to first sync everything again from the server and then copy the local mails to the maildir. However, you have to change the filenames (removing the UID and FMD parts is critical). Otherwise, OfflineIMAP might think they are already on the remote.

**Comment by zw963** [comment]
> This feature is not implemented. You have to mark them as read on one side so the flags get synced to the other side on next run.

this feature is  not intend to implement,  right ?

Thanks.

**Comment by nicolas33** [comment]
There's no plan to implement this feature. However, it should be easy enough to implement a post sync hook (supported) to do this job locally so that they are marked synced on next run.

**Comment by zw963** [comment]
Understood, thank for help.
