### ISSUE TITLE
What's the time used by Gmail to display the "sent" datetime?

### ISSUE THREAD

**Issue by XIAZY** [OfflineIMAP/offlineimap#331]
> This v1.0 template stands in `.github/`.

### General informations

- OfflineIMAP version: 6.6.1
- server name or domain: Gmail, Outlook
- CLI options:

```
Configuration file offlineimaprc goes here. REMOVE PRIVATE DATA.
```
[general]
accounts = Gmail
ui = Curses.Blinkenlights

[Account Gmail]
localrepository = GmailLocal
remoterepository = GmailRemote
autorefresh = 5

[Repository GmailLocal]
type = Maildir
localfolders = ~/Gmail

[Repository GmailRemote]
type = IMAP
remotehost = imap.gmail.com
ssl = yes
remoteuser = example@gmail.com
remotepass = password
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
folderfilter = lambda foldername: foldername in [r"[Gmail]/&XfJT0ZCuTvY-"]
```
The pythonfile file goes here (if any). REMOVE PRIVATE DATA.
```

### Log error

```
Nope.
```

### Steps to reproduce the error

- Sync the emails from Outlook account.
- Copy the emails to Gmail folder.
- Sync Gmail
- Times goes wrong

----
Hi.

I tried to copy emails from a different account and sync it to gmail by copying the email files. Unfortunately the time all goes wrong. Instead of displaying time for which the email was sent, the time displayed in Gmail webmail is the time when the synchronization was performed.

Please help me to solve it, thank you so much!

**Comment by nicolas33** [comment]
I wonder this feature is not implemented for the Maildir/IMAP use case. The remote INTERNALDATE is only fixed with the IMAP/IMAP use case. 

The date used in the filename is either the `Date` or `Delivery-Date` header but not the INTERNALDATE (IMAP). So, the information is lost as soon as the email is stored on disk.

With Maildir/IMAP, INTERNALDATE is set from the `Date` header or none if it is missing or not valid date.

I'm assuming that the "sent" date displayed by Gmail is the IMAP INTERNALDATE. I'm not sure this is true and this would require more checks. You might like to tune a `Date` header for a local email and see what happens.

**Comment by nicolas33** [comment]
Notice that Gmail might happily ignore the headers and INTERNALDATE dates while displaying a "sent" date so I'm not sure we can do anything in this area.

**Comment by XIAZY** [comment]
Indeed, the Gmail seems has a different method rather than date written in email's `header`.
I'll guess the problem is related to the filename? Seems like the problem is not related to `offlineimap` itself.
