### ISSUE TITLE
maxage is respected only once

### ISSUE THREAD

**Issue by mhavo** [OfflineIMAP/offlineimap#384]
#### General informations
- system/distribution (with version): OSX Yosemite 10.10.5 (14F1912)
- offlineimap version (`offlineimap -V`): homebrew offlineimap v7.0.7, imaplib2 v2.55 (bundled), Python v2.7.10
#### Configuration file offlineimaprc

```
ssl = yes
maxage = 100
status_backend = sqlite
type = GmailMaildir
```
#### Steps to reproduce the error
- Empty maildir
- sync -> mails newer than 100 days are synced normally
- change maxage to 200
- sync -> no new mails (there should be)
- remove maxage from config
- sync -> all mails coming... (17000)
- interrupt
- put maxage back
- sync
- all mails still coming, no way to get offlineimap respect maxage again...

**Comment by nicolas33** [comment]
> #### Steps to reproduce the error

> - Empty maildir
> - sync -> mails newer than 100 days are synced normally
> - change maxage to 200
> - sync -> no new mails (there should be)

Could you provide a log with `-d imap` enabled for this run, please?

> - remove maxage from config
> - sync -> all mails coming... (17000)
> - interrupt
> - put maxage back
> - sync

And yet another log for this one.

> - all mails still coming, no way to get offlineimap respect maxage again...

**Comment by mhavo** [comment]
That log seems to give a tons of information. Maybe too much, if privacy is in any value anymore?

**Comment by nicolas33** [comment]
You might send the logs to me directly by email.

**Comment by mhavo** [comment]
Some logs are on the way.

**Comment by nicolas33** [comment]
See in the git logs: https://github.com/OfflineIMAP/offlineimap/commit/a5e32929b6434b4a780a83af20df00025d6b92c8

**Comment by mhavo** [comment]
nicolas.s-**v@lapos**.net keeps bouncing...

**Comment by nicolas33** [comment]
I'm receiving lot of emails at nicolas.s-dev (laposte.net).

**Comment by mhavo** [comment]
Mail Delivery Subsystem <mailer-daemon@googlemail.com>
2:47 PM (21 hours ago)

to me 
Delivery to the following recipient failed permanently:

     nicolas.s-dev (laposte.net)

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain laposte.net by smtpz4.laposte.net. [194.117.213.1].

The error that the other server returned was:
550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN007_510


----- Original message -----

DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;

**Comment by nicolas33** [comment]
As a subsidiary mail, please try offlineimapproject (gmail.com).

**Comment by mhavo** [comment]
On the way...

**Comment by nicolas33** [comment]
Got it. I'll dig into this.

**Comment by nicolas33** [comment]
The maxage feature was broken so it had to be fully re-designed. At first, you may like to cautiously read http://www.offlineimap.org/devel/2015/04/14/why-we-changed-maxage.html.

When the local folder is empty, we compute the min_uid from the UIDs provided by the remote. That's fine. When the local side is empty, we compute the **min_uid** based on the local filenames.

When we scan the local folder, we check the datetime stored as timestamp in the prefix filename (the first numerical digits). The issue is that this value is the **download** datetime by default. IOW, we might consider very old emails (low UID) if they are downloaded recently (within the maxage range). As soon as we have a "wrong" low UID, we fail at finding the correct min_uid.

I think it's possible to change/add maxage only if `filename_use_mail_timestamp` is set to *yes* for the local repository since the **first run** **AND** that the all the emails are correctly formatted (otherwise, we fallback to the **download** datetime). This option will use the date found in the header for the prefix.

We might want to set `filename_use_mail_timestamp` by default when maxage is used. We might even want to set this option by default whatever maxage is used ot not. Also, it's possible to change of fallback strategy for wrongly formatted emails.

Also, we have to document those limitations.

**Comment by nicolas33** [comment]
> I think it's possible to change/add maxage only if filename_use_mail_timestamp is set to yes for the local repository since the first run AND that the all the emails are correctly formatted (otherwise, we fallback to the download datetime). This option will use the date found in the header for the prefix.

This is not enough. This would help while decreasing the maxage range (e.g.: 200 -> 100) but not while increasing it. To allow increasing the range, we must keep track on the min_uid/maxage value to check if maxage was changed or we would keep computing the same min_uid.

Also, I'm worried what would be done for the already downloaded emails that we'd next ignore while decreasing the range, because of the cache.

Allowing to change the maxage value is not easy.

**Comment by nicolas33** [comment]
I could come with something by updating the strategy a bit. Please try above patch.

**Comment by nicolas33** [comment]
Could you please try https://github.com/nicolas33/offlineimap/tree/ee94ba542374dc76049b285d6fbf0d1d2be94443 ?

**Comment by nicolas33** [comment]
Branch rebased on top of *next*: https://github.com/nicolas33/offlineimap/tree/b384

@mhavo @OfflineIMAP/collaborators If anyone using maxage could test this patch, please.

I'm postponing the next release because of this. Without positive feedback, this won't be included into the release.

**Comment by nicolas33** [comment]
Adding some mentions for above comment: @muggenhor @ff2000

**Comment by nicolas33** [comment]
It's possible to install offlineimap as a user: remove the currently installed offlineimap and download the zip (or `git clone` the repository). Then `./offlineimap.py [options]`.

**Comment by nicolas33** [comment]
@all I have mixed feelings about this issue. I think my patch would help but nobody tried it, actually. Does anyone using maxage could try the patch to check it doesn't hurt?

**Comment by aroig** [comment]
@nicolas33 I'll try to setup a testing replica sometime this week. I can't really test this with my normal mail...

Why your mixed feelings about this? Do you see any downside at checking first with the remote?

The idea of checking the remote first is for the scenario in which one has a full remote, a local replica truncated at maxage 100, and increases it to 200. Isn't it? Currently we would not get new messages despite the increased maxage.

Hmm... One problem with the remote first approach in this patch is if you keep a full replica locally, and the remote truncated at maxage (maybe due to quotas, etc). Then you hit the same problem in reverse when increasing the maxage. So it really shifts the problem to a different scenario.

The actual source of this problem is when the replica we use for the maxage check has gaps back in time (due to a previous more restrictive maxage). This can happen locally or remotely.

What about this? Let's decide whether to do local + `filename_use_mail_timestamp` first or remote first. I'm currently unsure what would be best.

Then, check for uids in range (that `len(uid) > 0`) AND check if there is any previous uid older than maxage. If this happens it means 2 things: the replica has messages within the maxage range, and we are not hitting a gap back in time. So the `min_uid` would be reliable. 

If this fails, do the same with the other replica. 

If it also fails for the other replica, it means your maxage range includes everything, so either take the minimum uid you got on both sides, or just disable maxage.

This assumes that there may be a single gap back in time, but after a certain point in time, the local messages are synced to the remote fully up to the present.

You could probably cook up replicas for which the procedure I propose would still fail. For instance sync for 10 days, wait for 100, and sync again with a maxage of 10. Then you have a 90 day gap in the middle of your local replica...

**Comment by nicolas33** [comment]
> Why your mixed feelings about this? Do you see any downside at checking first with the remote?

As usual. It looks fine to apply until we find regressions. :-)

> The idea of checking the remote first is for the scenario in which one has a full remote, a local replica truncated at maxage 100, and increases it to 200. Isn't it?

Actually, this should enhance most of the scenario. For the local side, we compute min_uid based on the file timestamps but they may vary with the configuration options (or due to some user/<any program> changes to the maildir).

> Hmm... One problem with the remote first approach in this patch is if you keep a full replica locally, and the remote truncated at maxage (maybe due to quotas, etc). Then you hit the same problem in reverse when increasing the maxage. So it really shifts the problem to a different scenario.

On remote truncation, I would expect to compute another min_uid on next run without any issue.

> The actual source of this problem is when the replica we use for the maxage check has gaps back in time

I think the issue comes from the way we compute min_uid based on the *download* time with some setups. If the user decides to change the maxage vaule, the result is unexpected.

> What about this? Let's decide whether to do local + filename_use_mail_timestamp first or remote first. I'm currently unsure what would be best.

Yes, this is something that could be done. I'm not sure this is the best alternative because we would add important complexity both in the code and in the configuration options for unusual (rare?) use cases.

> Then, check for uids in range (that len(uid) > 0) AND check if there is any previous uid older than maxage. If this happens it means 2 things: the replica has messages within the maxage range, and we are not hitting a gap back in time. So the min_uid would be reliable.

I don't get what you mean with "uid older than maxage". Going back in time should not be an issue.

> You could probably cook up replicas for which the procedure I propose would still fail. For instance sync for 10 days, wait for 100, and sync again with a maxage of 10. Then you have a 90 day gap in the middle of your local replica...

"Gap"? Trimming from 100 to 10 should mean: 

`ignore any mail with UID < min_uid where min_uid is the min UID with a date computed from the value of 10 days`

IOW, the min_uid is expected to change from run to run.

**Comment by aroig** [comment]
> Actually, this should enhance most of the scenario. For the local side, we compute min_uid based on the file timestamps but they may vary with the configuration options (or due to some user/ changes to the maildir).

Yes, I understand the download timestamp issue. You suggested `filename_use_mail_timestamp` for that, but then suggested it was not enough. I was making sure I understood the "not enough part".

> On remote truncation, I would expect to compute another min_uid on next run without any issue.

I do not understand. 

Let's say I have a huge local replica. I'm out of space on the imap server, and I decide to use `maxage = 100`, and remove messages older than 100 days from the imap server to make room.

Then, one day later I realize I better do `maxage = 365`. Using this patch, the next sync will do nothing. Since the remote has messages in the maxage range It will check the minimum uid in the 365-day maxage range on the remote, but the remote will return a uid from a message 100 days old. This uid will be used for the maxage thing, and none of the messages in the 100--365 days old range will be moved to the remote.

Am I mistaken? This problem mirrors the one that triggered this patch, but for the remote instead of the local replica.

> I think the issue comes from the way we compute min_uid based on the download time with some setups. If the user decides to change the maxage vaule, the result is unexpected.

Yes, we are mixing two problems here.

1. Using the local download time is wrong. You suggested the `filename_use_mail_timestamp` for that. (I'm not sure about the implications).

2. Increasing the maxage from say 100 to 365 may not sync the messages in the new maxage range which are not in the local replica. The min_uid is computed on a replica that has missing messages (a gap).

This patch is an attempt to solve both of them. I'm saying it does not solve 2. It just shifts it to a different scenario.

**Comment by nicolas33** [comment]
> Let's say I have a huge local replica. I'm out of space on the imap server, and I decide to use maxage = 100, and remove messages older than 100 days from the imap server to make room.
> 
> Then, one day later I realize I better do maxage = 365. Using this patch, the next sync will do nothing. Since the remote has messages in the maxage range It will check the minimum uid in the 365-day maxage range on the remote, but the remote will return a uid from a message 100 days old. This uid will be used for the maxage thing, and none of the messages in the 100--365 days old range will be moved to the remote.
> 
> Am I mistaken? This problem mirrors the one that triggered this patch, but for the remote instead of the local replica.

You're right. Increasing maxage sucks in this case. However, the patch does not pretend to fix this.

> I'm saying it does not solve 2. It just shifts it to a different scenario.

You're right. I think having both truncated on remote and increasing maxage is less usual than having wrong local computation. Also, we move from an "undefined behaviour" to something more predictive from the user POV.

I agree this is a matter of use case in the first place.

**Comment by nicolas33** [comment]
Now, I wonder we should compute the min_uid for both sides and take the min of the min_uid. :-)

**Comment by nicolas33** [comment]
(which would not be correct because of the local side hazard)

**Comment by aroig** [comment]
> (which would not be correct because of the local side hazard)

What are the downsides of using `filename_use_mail_timestamp` for that?

**Comment by nicolas33** [comment]
> What are the downsides of using filename_use_mail_timestamp for that?

I'd say that the extracts of the date are not all correct. This might worth a try, though.

**Comment by nicolas33** [comment]
Finally, I've decided to apply this patch.

**Comment by nicolas33** [comment]
And a regression finally found in #581. Not good.

**Comment by nicolas33** [comment]
> > What are the downsides of using filename_use_mail_timestamp for that?
> 
> I'd say that the extracts of the date are not all correct. This might worth a try, though.

Also, I would expect that the remote date is more reliable than the local one.
