### ISSUE TITLE
remotehost should not be required when preauth_tunnel is being used

### ISSUE THREAD

**Issue by iliastsi** [OfflineIMAP/offlineimap#503]
The latest version of OfflineIMAP now requires a remotehost even when preauthtunnel is being used. This is a regression from the previous version of OfflineIMAP (see also Debian bug [#879705](https://bugs.debian.org/879705)). The faulty commit seems to be 1ce596d713. @drscream Could you please comment on why you replaced preauth_tunnel with transport_tunnel instead of taking both into account?

**Comment by nicolas33** [comment]
I'll revert @drscream if the patch brings too much pain.

@iliastsi I'm thinking about releasing a v7.1.4 due to the reported regressions of v7.1.3.

**Comment by drscream** [comment]
Dear @iliastsi and @nicolas33,

I'm really sorry that this fix break some other issue. I will need to have a look and may create a fix for the fix asap. But I hope I could also try to explain it a little bit better:

From my understanding `preauth_tunnel` is used to authenticate at any host and connect to the hostname which is required. The `transport_tunnel` is an replacement for the `hostname` because that command is executed to provide an IMAP interface.

**Comment by drscream** [comment]
Additional to that it was totally my fault! I checked the code again and you're right we need to modify the code as below because both tunnels provides a regular IMAP interface at the end!

```
self.hostname = None if self.transport_tunnel or self.preauth_tunnel else repos.gethost()
```

**Comment by nicolas33** [comment]
Thank you very much for the quick fix!
Applied.

**Comment by iliastsi** [comment]
@drscream Thank you for the quick fix!

> @iliastsi I'm thinking about releasing a v7.1.4 due to the reported regressions of v7.1.3.

That would be great! Much appreciated.

-- 
Ilias
