### ISSUE TITLE
Support SHA-256 fingerprints in option "cert_fingerprint"

### ISSUE THREAD

**Issue by jkur** [OfflineIMAP/offlineimap#521]
Please support SHA-256 fingerprints in cert_fingerprint config variable.

For example riseup.net signs the validity off their fingerprint with their GPG-Key
but they only include the SHA-256 of the SSL-Certificate: https://riseup.net/en/security/network-security/certificates

Copying and pasting the fingerprint into cert_fingerprint fails, obviously because a SHA-1 fingerprint is expected.

#### General informations

- system/distribution (with version): Debian/buster
- offlineimap version (`offlineimap -V`): offlineimap v7.1.5, imaplib2 v2.57 (system), Python v2.7.14+, OpenSSL 1.1.0g  2 Nov 2017
- Python version: Python 2.7.14+
- server name or domain: mail.riseup.net
- CLI options: -

#### Configuration file offlineimaprc
[Repository Remote.riseup]
type = IMAP
ssl = yes
remotehost = mail.riseup.net
remoteuser = someuser
cert_fingerprint = ab1757631d84ba6f77cc0784fcbdccedd6268c217dbe625d53aa976d1de74123

#### Logs
*** Processing account riseup
INFO:OfflineImap:*** Processing account riseup
Establishing connection to mail.riseup.net:993 (Remote.riseup)
INFO:OfflineImap:Establishing connection to mail.riseup.net:993 (Remote.riseup)
ERROR: Server SSL fingerprint '92471a2f5f1082cc2752f308e0c5631a43f14af3' for hostname 'mail.riseup.net' does not match configured fingerprint(s) ['ab1757631d84ba6f77cc0784fcbdccedd6268c217dbe625d53aa976d1de74123'].  Please verify and set 'cert_fingerprint' accordingly if not set yet.
ERROR:OfflineImap:ERROR: Server SSL fingerprint '92471a2f5f1082cc2752f308e0c5631a43f14af3' for hostname 'mail.riseup.net' does not match configured fingerprint(s) ['ab1757631d84ba6f77cc0784fcbdccedd6268c217dbe625d53aa976d1de74123'].  Please verify and set 'cert_fingerprint' accordingly if not set yet.

#### Steps to reproduce the error

Use a SHA-256 fingerprint in cert_fingerprint option

Best regards!

**Comment by konvpalto** [comment]
Basically, you request the ability to use SHA-256 fingerprints for X.509 certificates (or, even better, not just SHA-1 fingerprints) which user can grab from some site, e-mail thread or other trusted place?  The reason I am asking is that here's what happens with the verification just now:
 - full DER-encoded (DER == binary ASN.1 form) certificate of the peer is processed by SHA-1 inside OfflineIMAP and hexadecimal digest is taken from that value;
 - the resulting hash is compared with the configured value(s) by cert_fingerprint.
This, basically, means that user (if posesses somehow verified server certificate) can do SHA-1 + hexdigest by himself and stick that into cert_fingerprint.  An advanced user, yeah.

On the other side, SHA-1 is getting considered harmful (not broken, but suspicious), so having a way to switch to the stronger hashes is a good thing.

I'd, then, propose (and will implement once we'll settle the details) the following design:
 - cert_fingerprint elements can have just bare fingerprint values that will now default to SHA-1;
 - any element can be prefixed by 'sha-256:' or 'sha-512:' (or whatever we will like to support): it means that this hash is of the corresponding type and server certificate is to be processed using this algorithm.

I thought about heuristics on the length of the elements of cert_fingerprint, but having SHA-256 and SHA-512/256 (and, also, SHA-224 + SHA-512/224) undermines this strategy.  Most probably, for good, since it is always better to be more explicit with the server verification bits.

Any views on this?

**Comment by nicolas33** [comment]
We could have another configuration option like `cert_fingerprint_type`. I don't have strong opinion on this unless we could have collisions with prefixes.

**Comment by nicolas33** [comment]
To make it clear, I wonder about a fingerprint starting with a prefix. If possible, we'll have to check the length of the key. So, it might be easier with a new configuration option.

**Comment by chris001** [comment]
* I believe there's a standard way to explicitly specify the hash type, by putting a prefix before the hash.  This comes from storing password hashes in database fields. Must research this to confirm.
* If not a standard way to prefix hash to indicate hash type, these hashes are different lengths, so the code can determine the hash type by measuring how many bits is the length of the hash.

**Comment by jkur** [comment]
Just for the record: @konvpalto's comment on how the fingerprint is actually calculated translates into a command like so:
```shell
openssl s_client -connect mail.riseup.net:993 -showcerts 2>/dev/null| openssl x509 -outform DER | sha1sum
```
Being a noob with openssl myself maybe this helps others.

Anyway. I was able to solve my problem with this description (calculating the fingerprint myself), but it would still be nice, if one could just put the sha256 or whatever fingerprint into the config file.

I would like to see the `sha256:xxyyzz...` variant. Having multiple options (like `cert_fingerprint_type`) is in my opinion tedious.
If there is some standard to specify hashes, that would be perfect.

**Comment by velleto** [comment]
I think that prefixing the fingerprint with it's type is also somewhat tedious. _Especially because it will break existing configuration files_.

The fingerprint is compared in the following lines I believe.
https://github.com/OfflineIMAP/offlineimap/blob/88197a7e9097a3774aa328c110d9a6692d4cf465/offlineimap/imaplibutil.py#L205-L207

I would suggest implementing the requested feature as follows
```
server_cert = self.sock.getpeercert(True)
hashes = sha512, sha384, sha256, sha224, sha1
server_fingerprints = [hash(server_cert).hexdigest() for hash in hashes]
matches = [(server_fingerprint in self._fingerprint) for server_fingerprint in server_fingerprints]

if not any(matches):
    raise OfflineImapError("Server SSL fingerprint '%s' "
    ...
```
Benefits:

- This does not require configuring an extra paramater such as `cert_fingerprint_type`.
- The user can configure their `offlineimap.rc` without any consideration to which type of hash they are using. This is especially kind to less experienced users. @konvpalto has already pointed out that usage of this feature already has a requires users to be fairly advanced.
- No complicated parsing of "hash type prefix" needed in code.
- Current configuration files do not need to be changed with feature implemented this way.

Security concerns:

- Potential downgrade attack. The client configures their `offlineimap.rc` with a fingerprint using hashing algorithm `stronghash`. Assuming an attacker can easily create fake certificates with the same fingerprint as the real cert using `weakhash` (by collision) but cannot fake the fingerprint with `stronghash`, then the proposed code will still verify the fingerprint as being correct. This can only occur if `weakhash` and `stronghash` return hashes of the same `.hexdigest()` length.
 The [Wikipedia page on secure hashing algorithms](https://en.wikipedia.org/w/index.php?title=Secure_Hash_Algorithms&oldid=837517049) shows that each of the above algorithms output different length hashes. So I don't think this kind of attack is even possible. And even if it was, that assumes that any of the `sha1-512` are considered _"weak"_, which they aren't.
Absolute worst case, the fingerprint is downgraded to the weakest available hash, `sha1`, which the current hash, and the user has a false sense of security because they thought only `stronghash` was in use.

Additional Notes:
- If this is implemented, I would also suggest allowing users to leave the `:` in the finerprint in their configuration file. This is really easy to implement, and leaves for slightly easier configuration. I mention this because `openssl`, along with other tools, gives fingerprints in the following format 
```
$ openssl x509 -in certfile.pem -sha1 -noout -fingerprint
SHA1 Fingerprint=D0:83:13:3D:99:99:0F:80:0A:B5:58:C4:51:27:13:81:45:8E:74:F0
```
meaning that the user cannot just copy and paste it. I appreciate that this is just a minor gripe.
I would suggest implementing this by using `string.replace()` on the user-provided fingerprints to remove the colons. Something like
```
plain_fingerprints = [fingerprint.replace(':', '') for fingerprint in self._fingerprint]
```

**Comment by chris001** [comment]
Enabling DNSSEC DANE TLS in the IMAP connection will solve this issue at the server level (for IMAP servers where DANE TLS is configured). 
This way of dynamically computing all 5 SHA hash lengths appears to be a compatible practical fallback method to solve this issue (some IMAP servers now only use stronger SHA hash types than originally anticipated) with no impact to offlineimap client configs.

**Comment by nicolas33** [comment]
You have good ideas. Please, talk in patches!

**Comment by nicolas33** [comment]
Patches applied: 356bd0b78f4466adb97a3ab9d5dab1289aad312b. This will be in next release (after v7.2.0).
Thank you all.
