### ISSUE TITLE
Offlineimap won't terminate 

### ISSUE THREAD

**Issue by amandabee** [OfflineIMAP/offlineimap#537]
I'm using `pass` to store passwords so when offlineimap runs I have to unlock the Pass vault. If I don't, offlineimap hangs and I can't force it to quit and can't run it anywhere else because it can't lock the account. The only way to run offlineimap is to completely log out of my account. 

```
OfflineIMAP 6.6.1
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync Example:
 *** Processing account Example
 ERROR: Could not lock account Example. Is another instance using this account?
 *** Finished account 'Example' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: Could not lock account Example. Is another instance using this account?

Traceback:
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 262, in syncrunner
    self.__lock()
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 220, in __lock
    fcntl.lockf(self._lockfd, fcntl.LOCK_EX|fcntl.LOCK_NB)

```

#### General informations

- system/distribution (with version): **Ubuntu 16.04 LTS**
- offlineimap version (`offlineimap -V`): **6.6.1**
- Python version: 2.7.12
- server name or domain:  local
- CLI options:  none

#### Configuration file offlineimaprc

```
[general]
accounts = Example
pythonfile = ~/.offlineimap/pass.py

[Account Example]
localrepository = Local
remoterepository = Remote
status_backend = sqlite
postsynchook = notmuch new

[Repository Remote]
type = IMAP
remotehost = mail.example.com
cert_fingerprint = 2e09649a...45013f082
remoteuser = username@example.com
remotepasseval = get_pass("username")
ssl = yes

[Repository Local]
type = Maildir
localfolders = ~/Maildir
restoreatime = no
```

#### pythonfile (if any)

pass.py reads: 
```
#! /usr/bin/env python2
from subprocess import check_output


def get_pass(account):
    return check_output("pass Example/" + account, shell=True).splitlines()[0]

```

#### Logs, error

```
I don't see any logs for offlineimap. 
```

#### Steps to reproduce the error

-  run `offlineimap`
-  wait for the popup to ask for the passphrase to unlock  `pass` 
-  enter the wrong password or just close the popup without entering a password
-  offlineimap will just hang. Use <kbd>ctrl</kbd><kbd>c</kbd> to force quit and screen reads: 

> ^CTerminating NOW (this may take a few seconds)...

-  offlineimap never terminates, and the lockfile remains.

**Comment by amandabee** [comment]
What do I replace `status_backend` with? 

```
OfflineIMAP 7.1.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.57 (bundled), Python v2.7.12, OpenSSL 1.0.2g  1 Mar 2016
Account sync Velociraptor:
 ERROR: the 'status_backend' configuration option is not supported anymore; please, remove this configuration option.
ERROR: Exceptions occurred during the run!
ERROR: the 'status_backend' configuration option is not supported anymore; please, remove this configuration option.

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 270, in syncrunner
    self.statusrepos = Repository(self, 'status')
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/__init__.py", line 58, in __new__
    return LocalStatusRepository(name, account)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 45, in __init__
    OfflineImapError.ERROR.REPO

```

**Comment by amandabee** [comment]
Seems to be working.

**Comment by chris001** [comment]
Thanks @amandabee 
* @nicolas33 we should contact the ubuntu maintainers, and ask them to update their package immediately to 7.1.5, in ubuntu 14.04LTS, 16.04LTS, and 17.04, because probably many other users are experiencing these same old bugs which exist in the old versions and fixed now in 7.1.5.
https://packages.ubuntu.com/search?keywords=offlineimap
https://packages.ubuntu.com/trusty/offlineimap (packaging 6.5.4-2 this is many years outdated! yet the OS is supported until April 2019...)
https://packages.ubuntu.com/xenial/offlineimap (6.6.1 also obsolete, OS supported until April 2021)
https://packages.ubuntu.com/artful/offlineimap (7.1.2 also unsupported old version).
Here's the email: ubuntu-motu@lists.ubuntu.com

* Either have the maintainers update (above), or dynamically prompt the user to let `offlineimap` self update to current supported version, then run the command `pip install -U offlineimap`.

**Comment by nicolas33** [comment]
There is no bug about the lock. The message says 

```
Could not lock account Example. Is another instance using this account?
```

and another instance was running, AFAICT. Killing it released the lock.


About the call to `pass`, I don't know. Feel free to request the distrib maintainers about this. They tend to be conservative sometimes and they have their own reasons to.

**Comment by amandabee** [comment]
I couldn't kill it, though. There was no way to kill it and release the lock until I upgraded to 7.1.5.

**Comment by chris001** [comment]
@amandabee 
Could you share the exact sequence commands you ran. This would help us to understand exactly how this issue resolved on your system. Did you only run the upgrade command and re-run the command to sync mail? Or did you run other commands also. Which commands and in which order would be great to have.

**Comment by nicolas33** [comment]
> I couldn't kill it, though. There was no way to kill it and release the lock until I upgraded to 7.1.5.

It's possible to kill any process in Linux with a "hard" kill (`kill -9`, cf. `man 7 signal`) unless it became a zombie (marked `Z`). Only a reboot can fix zombies. For offlineimap I've never seen a process to become a zombie but it can because of I/O issues. You might like to set socktimeout to prevent from network I/O, BTW.

The upgrade won't fix already running instances of offlineimap.
Since v6.7.0 we support hard kill via 3 `ctrl+c`.

**Comment by amandabee** [comment]
When you say "You might like to set socktimeout to prevent from network I/O, BTW." -- where would I set that?
