### ISSUE TITLE
Files are duplicated if syncing on 2 machines both synced with rsync/syncthing

### ISSUE THREAD

**Issue by edi9999** [OfflineIMAP/offlineimap#543]
#### General informations

- system/distribution (with version): Fedora release 27 (Twenty Seven) 
- offlineimap version (`offlineimap -V`): offlineimap v7.2.0, imaplib2 v2.57 (bundled), Python v2.7.14, OpenSSL 1.1.0h-fips  27 Mar 2018
- Python version: Python 2.7.14
- server name or domain: 
- CLI options: none

#### Configuration file offlineimaprc

```
NOT RELATED TO THE ISSUE
```

## Usecase

I have an issue with my particular setup, I think it is related to how offlineimap sync mechanism is designed.
My problem is as follows : 

I have two computers at home, both of which contain all my email in ~/Mail

Between those computers, I run "Syncthing" which is a Program that makes it possible to "sync" two folders on two computers on the same network, much like dropbox but it is open-source software.

The computers share the ~/Mail folder with syncthing.

The problem is that when I go on my computer2 (edgar-inspiron), after waiting for the completion of syncthing, if I run offlineimap on computer2, my email data is downloaded again with slightly different names, so I have all emails duplicated in my ~/Mail folder. 

If I run `fdupes` to find duplicated files in my ~/Mail folder, I see that many many files are duplicated, for example : 

```
./INBOX.archive/cur/1517039684_0.2297.edgar-Dell,U=3820,FMD5=6ec33b7708e41596e6d4f5707101ac47:2,S
./INBOX.archive/cur/1517215967_5.15451.edgar-Inspiron-7720,U=3820,FMD5=6ec33b7708e41596e6d4f5707101ac47:2,S 
```

There are lots and lots of other duplicated files like this (8568 according to `fdupes -R .  | wc -l`)

As you can, see, both files differ by hostname (one of them is edgar-Dell, which is my most used computed, and the other is edgar-Inspiron-7720 which is my not so often used computer), but they have the exact FMD5.

It seems to me that the mechanism to "know" that a file was already downloaded before is not robust enough, especially if the file was downloaded on an other hostname. 

I think it could be possible to reproduce the issue by running offlineimap on one computer with hostname foobar1, then copy the ~/Mail folder to an other computer with hostname foobar2 and run offlineimap from that second computer.

Is this issue clear enough ? What do you think ?

**Comment by nicolas33** [comment]
Yes, it's not possible to have both computers synced to the server with offlineimap if both are synced via rsync/syncthing/whatever.

It's because the filenames in the maildir is not deterministic.


*The email "A" on the IMAP server gets one filename "A1" on c2 with the sync chain offlineimap-c1/syncthing and another filename "A2" (still not known as synced by offlineimap-c2) from the offlineimap-c2 sync.* Notice the order is not relevant.

However, you can fix this by syncing the cache of offlineimap with syncthing, too. This way, the above use case becomes:
 
*The email "A" on the IMAP server gets one filename "A1" on c2 with the sync chain offlineimap-c1/syncthing. With the next offlineimap-c2 sync, "A1" is marked as already downloaded from the previous c1-c2 sync including the cache.* No duplicate. 

Be care to always keep the same version of offlineimap on both c1 and c2.

**Comment by edi9999** [comment]
Ok, I see, I just have to sync `$HOME/.offlineimap` too and it should work automatically.

**Comment by edi9999** [comment]
I'm keeping yet another backup of my email, so if it breaks one day, I will still be able to recover.
