### ISSUE TITLE
Broken dates by using mbsync

### ISSUE THREAD

**Issue by ZaxonXP** [OfflineIMAP/offlineimap#628]
For a long time I was using offlineimap to sync my local mail folders with Gmail. It was fine except that I could not manage to get work around of the labels with the UTF characters (on the Gmail the labels were fine, but local folders had strange characters). So I decided to try mbsync (I know, my bad), but it did change the dates of the e-mails, so now Gmal web interface displays old e-mails as they were received recently (the mbsync updated the e-mails using sync date). Also I noticed that it making some mess with duplicate messages. 

I wonder if offlineimap would be able to fix these dates and sync the update to Gmail. Would it be possible to add such feature in one of the next releases?

The date is intact in every e-mail header and Gmail display these correctly if you open the original. But in the list view the dates are wrong (also searching is not possible using the original dates).

**Comment by nicolas33** [comment]
Trying mbsync might be a good thing. This helps other users to do what they expect.

I'm afraid the date used on the server is beyond offlineimap or any other IMAP client. Which date is used is a server feature we don't have access to.

**Comment by ZaxonXP** [comment]
I found this description about the problem on the following [page](https://wiki.archlinux.org/index.php/Isync). Here is what is says:

> Emails on remote server have the wrong date
This fix works when syncing with fastmail, but it likely applies to other services as well.

>If you move an email to a new folder using an email client, and mbsync causes the email to appear with the wrong date on the server, add this to your configuration file:

`CopyArrivalDate yes`
> For example, without this setting, moving an old email from Inbox to Archive using mu4e and then syncing to fastmail with mbsync will cause the email to appear in Archive but with the date of the sync.

> mbsync uses mtime of email message when uploading from maildir to imap server. You can use fix_maildir_mail_mtime.py script to set mtime from email header.

The [script](https://gist.github.com/artizirk/877ce9d30159323aac037e2a2af74509) itself is Python code and afterwards mbsync can "fix" the damage. Unfortunately I was not able to do so, but I thought that offlineimap could incorporate such feature to extend the functionality and allows user to fix their problem.

What do you think about?

**Comment by nicolas33** [comment]
By default offlineimap does not use the mtime (unless it's configured otherwise). When uploading a email, the date is looked up in the following order:

1. INTERNALDATE
2. Header Date.
3. Let the server use the upload date time.

So, there's no issue with offlineimap.

Offlineimap won't upload emails it already synced to avoid duplicates. So, the correct way to make offlineimap set the date on the server again would be to move the emails out of the maildirs in the local side for each folder. Notice I say the **emails**, not the folders. The structure of the folders must be kept as-is. Sync with offlineimap to remove the emails on the remote.  Locally, restore the emails back into their original folder. Sync again. Then, the emails are uploaded to the server (to the remote empty folders) and the dates are restored according to the above policy.

IOW, this would be similar to restoring a local backup.

**If you'e about to try this, keep in mind to make a local backup before proceeding.**

**Comment by nicolas33** [comment]
I think we won't add features anymore to offlineimap because it's python2 only and that python2 is reaching its end of life.
