### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by franva** [OfflineIMAP/offlineimap#670]
#### General informations

- system/distribution (with version): Ubuntu 18.04
- offlineimap version (`offlineimap -V`): latest
- Python version: 2.7
- server name or domain: 
- CLI options: 

With the whole world moving away from Python 2, is supporting Python 3 on the table?

**Comment by chris001** [comment]
Absolutely, it's just a matter of gathering up and dedicating the time, energy, and resources.. this has been discussed in other issues also!

**Comment by franva** [comment]
I just found this project and read through the Readme and found this project is going to be replaced by
[Imapfw](http://github.com/OfflineIMAP/imapfw). But once opened imapfw on Github, it seems the last commit was a few years ago.

So do you know which one is going to be maintained?

Thanks

**Comment by chris001** [comment]
Which one is going to be maintained. Great question.  Right now, this project is getting more issues, maintenance, and contributions.  Our two main goals, if you ask me, are 1. to port to this project to python3, and 2. develop imapfw which itself is a modular redesign for easier maintenance, testing, and updates.  My short answer is, both!  More this one in the immediate time frame, and as imapfw gets to be fully developed and ready for alpha and beta release, more imapfw.  Are you wondering which code to contribute to?

**Comment by nicolas33** [comment]
> My short answer is, both! More this one in the immediate time frame, and as imapfw gets to be fully developed and ready for alpha and beta release, more imapfw.

Yes, exactly this. We are in the middle of something unachieved. The state of the projects is:

1. The current offlineimap works fine with python2.
2. Supporting both python2 and python3 could not be done. Porting offlineimap to python3 without python2 support is much easier to do and a good have. With one or two enthusiast developers this could be done in one or two months (not full time).
3. imapfw is something new but it's not working.

As the maintainer of offlineimap for years, I still maintain offlineimap for python2 but with minimal efforts. I intend to target imapfw and to work on this when I'll have free time (don't know when, though). The best short answer is for one or two developers to get involved in a fork of offlineimap for python3 only.

**Comment by franva** [comment]
thanks @chris001  and @nicolas33 

Just wondering why do we want to keep Python2 support when porting to Python 3?

I am sure many users will be happy with Python3 support even without Python2 support.

**Comment by TheRojam** [comment]
i think just get rid off Python2 is very fine. who needs really python? its more than EoL..

**Comment by chris001** [comment]
`Python2` version is maintained for now as a baseline to compare any `python3` ported version.  We need to compare `python3` dev version back to the `python2` working version, which is the only version that is fully working as of right now.

**Comment by scottkosty** [comment]
Along the same lines as chris wrote, porting from Python2 to Python3 is not trivial. It is difficult to get everything perfect, and even if everything is done "correctly" there's a chance that a bug in offlineimap that for whatever reason did not affect the Python2 version happens to affect the Python3 version. Similarly, although the Python3 version will be tested, there's lots of variation across Python3 versions. What is the minimum requirement that we need? Python has fixed a lot of bugs throughout their Python3 development. We can only test with the versions we have on our computers. We cannot guarantee that the versions other users have will work, and thus it's nice to allow those users to fall back on the Python2 version for at least some time, and it will be helpful for tracking down which bugs are due to different Python3 versions.

**Comment by nicolas33** [comment]
Sorry if I wasn't clear. We tried to support both py2 & py3 when this made sense, years ago. Today, there are much better chances to get this done exactly because it's possible to get rid of the py2 legacy support. Porting offlineimap to py3 only is much easier than what we tried (and failed) in the past.

I think that python 3.7 is the best version to start with.

**Comment by prometheanfire** [comment]
Gentoo has now masked offlineimap (meaning we are gonna remove it on July 4th it looks like, given the comment on the masking).

**Comment by nicolas33** [comment]
Thank you @prometheanfire for the feedback.

**Comment by heroin-moose** [comment]
@scottkosty, there will be no Python2 in modern distributions in a few months. So there is nowhere to fall back to.

**Comment by mbucas** [comment]
There are many ways to run Python 2 even if your current distribution doesn't support it any more:

- You can run a virtual machine with an older distribution of Linux (or FreeBSD, or even Windows)
- You can create a `chroot` of an older distribution (for example https://wiki.debian.org/chroot) and run Python 2 inside
- You can compile Python 2 yourself. Even if it's not supported, it can still compile and run fine !
- And probably other ways with various levels of complexity

The risks are the same for these solutions: there is no support for Python 2 so any security bug will remain wide open. The best isolation level is probably the virtual machine, but you will have to make your checks.

Anyway thanks to the maintainers of OfflineIMAP for working on porting to Python 3.

**Comment by limansky** [comment]
Just for your info, I've just found that offlineimap was removed from Gentoo portage because of Python 2 deprecation.

**Comment by mbucas** [comment]
As I'm also using Gentoo, I've backed up the ebuild in my personal overlay:
https://github.com/mbucas/gentoo-overlay

**Comment by thekix** [comment]
Hi,

I just create some patches for python3. Check them at https://github.com/thekix/offlineimap

I tested it with gmail, protonmail without problems. My repo is unstable, I will make more changes to remove python2 code.

Comments are welcome.
Regards,
kix

**Comment by nicolas33** [comment]
That's great news!

From a partial quick review:
- some 2to3 changes looks weird if not wrong.
- I've seen patches which should be "backported" here!

**Comment by rdslw** [comment]
I'm willing to help with python3  support financialy. It's not much but I can chip in, 100EUR per month for six months (via github sponsor?) for anyone willing to do a complete work on it. Anyone interested, please write here. Maybe also others can also help with sponsoring it.

**Comment by chris001** [comment]
In the middle of a move at the moment, so when the move in is complete, computers setup, I'll be glad to contribute `py3` tests and code!  I'm sure tests are the key to getting it right, with the least amount of uncertainty, and keeping it bug free!

**Comment by thekix** [comment]
Thanks.

I am working on it. I need some days to complete it.

**Comment by nicolas33** [comment]
Yes, I think that opencollective.com is the way to go.
Since @thekix started a fork we can redirect py3 contributors there. Also, I can help by providing feedbacks on technical requests.

@thekix: We could make announces on tweeter, on the blog and on the github front page about this if you'd like to. We could open a new project in the github OfflineIMAP organization and grant you maintainer privileges (so you're free to do whatever you want in the py3 fork) with better official support from the organization. I think this will help long-time users and distrib maintainers to track your progress (and this could help to get contributions, too).

**Comment by nicolas33** [comment]
https://opencollective.com/offlineimap-organization

**Comment by rdslw** [comment]
@thekix I will contact you on your email given on your profile, re contribution via github sponsor program or other.

**Comment by chris001** [comment]
@rdslw  Please contribute thru the [Sponsor](https://opencollective.com/offlineimap-organization) button, at the top of this page.

**Comment by thekix** [comment]
Hi,

@nicolas33 Thanks a lot.

About this:

_@thekix: We could make announces on tweeter, on the blog and on the github front page about this if you'd like to. We could open a new project in the github OfflineIMAP organization and grant you maintainer privileges (so you're free to do whatever you want in the py3 fork) with better official support from the organization. I think this will help long-time users and distrib maintainers to track your progress (and this could help to get contributions, too)._

I agree but I would like to start in the current fork. When I have something running and stable, then I think is better move it to a new project in the OfflineIMAP organization. Please, wait some days to have an 'alpha' version :-)

**Comment by nicolas33** [comment]
That's fine, of course. You know you're welcome. Ping me when you think it's the right time. ,-)

**Comment by nicolas33** [comment]
@chris001 I think that direct financial support is fine, too. That's less transparent for the org but it's without intermediation fees.

**Comment by thekix** [comment]
Hi!

I am ready. What I did?

- I removed bundled_imaplib2 and virtual_imaplib2, now I am using imlib2 (python3) from system (I am using Debian)
- I can download IMAP and Gmail Folders
- I can download (sync?) IMAP and Gmail Mails
- Mail flags seems to work

Therefore I think we can start now with the new project. @nicolas33 Please, create it, and include the current python2 v7.3.0 code on it. I will upload the changes this evening.

Thanks!

**Comment by nicolas33** [comment]
Done!

1. I've created the [OfflineIMAP/offlineimap3](https://github.com/OfflineIMAP/offlineimap3) repository.
2. I've pushed the branches (master and next only) from your fork.
3. I've created the [Maintainers (offlineimap3) team](https://github.com/orgs/OfflineIMAP/teams/maintainers-offlineimap3) in the OfflineIMAP organization with admin rights on the offlineimap3 fork.
4. I've invited @chris001 as a Maintainer, too.
5. You are invited to the 'Maintainers (offlineimap3)' team, and member of other repositories (website, documentation) because this could be usefull.

@thekix  Rodolfo, once the invited will be accepted you'll be the official maintainer of the python3 fork so you can manage it freely. Please, ping me if you're lacking rights to something. We'll later have to discuss about more rights like joining the Maintainers of the OfflineIMAP organization and full access to the twitter account.

TIP: What to do next?
a) Update the README.
b) Create a new release.
c) Adjust the public branches of the official fork.
d) Make announces (blog, twitter).

Of course, I can help you at any step. Feel free! ,-)

Welcome!

**Comment by thekix** [comment]
Hi!

thanks a lot @nicolas33 

I uploaded some patches more. 

__What we have in offlineimap3?__

- python2 is not used
- six (python compatibility library) is removed
- imaplib2: we use the installed in the system (pip install imaplib2, pip version 3)
- rfc6555: we use the installed in the system (pip install rfc6555, pip version 3). selectors2 is a dependency and is installed too.
- Code is more clear, less pylint warnings
- we can download the mail from imap and gmail
- we can store the mail using Maildir

We have a unstable version, but IMO the migration to python3 is done. The issue now is not support python3, the issues now are we need implement (migrate) the interface between offlineimap3 and imaplib2 (for python3). For this reason, _IMO, we can close this bug and open multiple bugs in offlineimap3 project._

__What is the problem and how to solve migrating the interface between offlineimap3 and imaplib2?__

The main issue is imaplib2 returns byte objects (or structs with byte objects), but offlineimap3 is using strings (like offlineimap). Then, some functions fail. How to solve this problem? It is very easy, we need check the returned values from imaplib2 in the offlineimap3 calls when something fails.

Examples:

- https://github.com/OfflineIMAP/offlineimap3/pull/1/commits/b24687fcd60dce4d6eb9cc07d2bb207eaa9893d9
- https://github.com/OfflineIMAP/offlineimap3/pull/1/commits/8e63f58b22dec40d761a0a6ed54fa183aa069656

__Then?__

Now, IMO, we can have offlineimap (v2) and offlineimap3 in the system. We can start testing offlineimap3 and start to open issues in the new project. But, this is not my code, is our code, all of us can start to sending patches.

Best regards!
kix

Note: We must not change imaplib2 in our systems. Some things in imaplib2 seems to fail (timeouts,...) so we should send patches to imaplib2.

**Comment by rdslw** [comment]
FYI, I started 50/month sponsorship for both @thekix and org. I assumed that the org have inside @nicolas33 and @chris001 so you can make use of this. 

Thank you all for your work!

**Comment by thekix** [comment]
@rdslw Thanks a lot!!

Sorry, I cannot reply to you directly because I deleted the mail testing offlineimap

**Comment by nicolas33** [comment]
Thank you much @rdslw . I've started a [thread here](https://github.com/OfflineIMAP/offlineimap/issues/679) to decide how and when to use the budget.

**Comment by nicolas33** [comment]
@thekix The bundled version of imaplib2 has diverged from upstream. I've merged patches sent to upstream in offlineimap since imaplib2 has stalled.

**Comment by thekix** [comment]
@nicolas33 I see the differences between imaplib2 and upstream. IMO we should take a decision about imaplib2.

**Comment by nicolas33** [comment]
I've merged the patches into the py2 version of imaplib2 only. Some might apply to the py3 version, too.
You're correct about imaplib2. I've provided details in our other thread.

**Comment by nicolas33** [comment]
offlineimap3 is the project to get offlineimap to work with python3.
