### ISSUE TITLE
Several mbnames sections

### ISSUE THREAD

**Issue by teto** [OfflineIMAP/offlineimap#76]
Hi,

I would like to generate several files via different mbnames sections. I've tried putting 2 mbnames sections (one to generate the mutt mailboxes, the other to generate my .checkmailrc); but only the last one gets interpreted. 
If there is a possibility to upstream, I may write a patch.

**Comment by nicolas33** [comment]
I think you're going ahead of a lot of complexity for a few benefit with multiple mbname sections.
I guess a postsync hook might actually do the trick.

Anyway, you are digressing the purpose of mbname and I think a very few people will ever use the requested feature.

That's why I'm closing this issue. If any other maintainer (@konvpalto @xnox @spaetz or @X-Ryl669 ) wants to dig into this he will re-open it.
