### ISSUE TITLE
messages in 'new' in a Maildir should not have any flags

### ISSUE THREAD

**Issue by doy** [OfflineIMAP/offlineimap#80]
Currently, offlineimap creates new messages with a trailing `:2,`, even when they are in the `new` folder. This doesn't follow the spec (http://cr.yp.to/proto/maildir.html) which says that renaming from `uniq` to `uniq:info` should only happen when moving from `new` to `cur`. This is currently causing an issue with notmuch, because notmuch assumes that all messages with info attached are supposed to be in `cur`.

**Comment by nicolas33** [comment]
Thinking about this more, we are right at putting the flags. We DO WANT flags even if it's new.

The reason is that IMAP servers allows this and we want our local to reflect the server the best we can. I use this feature often, mutt allows this too. So, I'll keep things as-is.

What could be done though is implementing a configuration option about that. This should not be hard to do but I'll not write it myself. Hence, I close.
