### ISSUE TITLE
lots of unnecessary cpu wakeups

### ISSUE THREAD

**Issue by doy** [OfflineIMAP/offlineimap#81]
It seems that when offlineimap is sleeping between syncs, it's being woken up every 50ms for some reason (strace shows repeated `select(0, NULL, NULL, NULL, {0, 50000})     = 0 (Timeout)` lines). This is not great for battery usage. I traced this down to the implementation of Condition.wait in python2's threading.py module (the equivalent code in python3 doesn't appear to have this problem, although I didn't look too deeply, and I'm not incredibly familiar with python). I'm not sure what offlineimap is using this method for, but it'd be nice if it could find a way to do it that didn't require polling with such a short interval.

**Comment by spaetz** [comment]
Yes, at least in python2, that is a problem. The thing is, that our main thread needs to be able to be interrupted by signals such as Ctrl-C.

This is function threadutils.py:exitnotifymonitorloop
As described in the comment, we need a timeout in that .get() call or Ctrl-C will never be catched (and we could potentially freeze forever without timeout). http://bugs.python.org/issue1360
On the other hand, a timeout will cause Python to wake up repeatedly (every 50ms if I remember correctly). I think it won't wake up if no timeout was specified.

Apparently this was fixed in python 3.2 so, we might be able to improve this in a Python3 world.

**Comment by nicolas33** [comment]
Thank you much for your input spaetz!

@doy 
Could you test https://github.com/nicolas33/offlineimap/tree/bug/81/cpu-wakeups please?

This is a hugly hack I wouldn't expect to solve all issues while it could effectively improve things a bit.

**Comment by nicolas33** [comment]
Got negative feedbacks in the mailing list. There are other offenders in the best case and it doesn't address the issue at all in the worse case. Discarding above patch.

**Comment by dolohow** [comment]
I can confirm that using Python3 solves the problem entirely.  As Python3 support is on the way I would rather close this issue or add some new label.

**Comment by nicolas33** [comment]
Will close with Py3 support.

**Comment by nicolas33** [comment]
Fixed in 1894a8f871771c71982e87f8eb26084aaa33fca4.
The fix is only valid when using Python 3, though.
